### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lapalipi** [tangxiaofeng7/Suscan#1]
请问下师傅：
ERROR: Service 'server' failed to build: The command '/bin/sh -c cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone' returned a non-zero code: 1
咋解决

**Comment by tangxiaofeng7** [comment]
你试试将 Dockerfile 第六行，修改成我这个格式。
```
RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
```
如果还是报错，建议你升级成最新的docker

**Comment by tangxiaofeng7** [comment]
是版本的问题，已经复现核实了。 手动修改成下面的格式

```
ENV LC_ALL C.UTF-8
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```
